version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9600:9600'

  vectorizer:
    build: ./vectorizer-python
    container_name: vectorizer
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
    depends_on:
      - opensearch

  api:
    build: ./api-node
    container_name: api-node
    environment:
      - OS_NODE=http://opensearch:9200
    ports:
      - '8000:8000'
    depends_on:
      - opensearch
